---
# meta tags
default_title: "Life Reboot Book | Download Free Workbook | Sarah Wall "
default_description: "Life Reboot: An Inner Wisdom Guide To Finding Your Passion and Purpose, by Sarah Wall. Be inspired to look within to find answers to life's questions."
default_image: "https://liferebootbook.com/images/lifereboot-book.png"

# social media
facebook: "bodymindspiritcoach"
fb_id: 1205828536110926 #this is for mind body spirit coach page

# variables
google-analytics-id:

# modules
skrollr: false

# site config
prod_url: "http://lifereboot.com/"

env: development

permalink: pretty
source: ./source
baseurl: /

# Conversion
incremental: true

# sass
sass:
  style: :compressed
