---
# meta tags
default_title: "Life Reboot Book | Download Free Workbook | Sarah Wall "
default_description: "Life Reboot: An Inner Wisdom Guide To Finding Your Passion and Purpose, by Sarah Wall. Be inspired to look within to find answers to life's questions."
default_image: ""

# social media
facebook: "bodymindspiritcoach"
linkedin: "https://ca.linkedin.com/in/sarah-wall-7a530b105"
google_plus: "http://google.com/+Bodymindspiritcoach777"
youtube: "https://www.youtube.com/channel/UCjVlPzd2tAD33H7BBvI0d2A"

# variables
google-analytics-id:

# modules
skrollr: false

# site config
prod_url: "http://lifereboot.com/"

env: development

permalink: pretty
source: ./source
baseurl: /

# Conversion
incremental: true

# sass
sass:
  style: :compressed
